name: manage-azure-policy-2dd4ac45
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Diagnostic_Settings_for_Automation_to_Log_Analytics_workspace_Deploy-Diagnostics-AA/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Activity_Log_to_Log_Analytics_workspace_Deploy-Diagnostics-ActivityLog/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Kubernetes_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-AKS/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Batch_to_Log_Analytics_workspace_Deploy-Diagnostics-Batch/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_CDN_Endpoint_to_Log_Analytics_workspace_Deploy-Diagnostics-CDNEndpoints/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Cognitive_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-CognitiveServices/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Cosmos_DB_to_Log_Analytics_workspace_Deploy-Diagnostics-CosmosDB/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Databricks_to_Log_Analytics_workspace_Deploy-Diagnostics-Databricks/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Factory_to_Log_Analytics_workspace_Deploy-Diagnostics-DataFactory/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Data_Lake_Store_to_Log_Analytics_workspace_Deploy-Diagnostics-DataLakeStore/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_subscriptions_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_System_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSystemTopic/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridTopic/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Hubs_to_Log_Analytics_workspace_Deploy-Diagnostics-EventHub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Front_Door_to_Log_Analytics_workspace_Deploy-Diagnostics-FrontDoor/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_HDInsight_to_Log_Analytics_workspace_Deploy-Diagnostics-HDInsight/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_Deploy-Diagnostics-KeyVault/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_integration_service_environment_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsISE/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_Workflow_runtime_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsWF/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_MariaDB_to_Log_Analytics_workspace_Deploy-Diagnostics-MariaDB/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Machine_Learning_workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-MlWorkspace/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Database_for_MySQL_to_Log_Analytics_workspace_Deploy-Diagnostics-MySQL/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Database_for_PostgreSQL_to_Log_Analytics_workspace_Deploy-Diagnostics-PostgreSQL/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Power_BI_Embedded_to_Log_Analytics_workspace_Deploy-Diagnostics-PowerBIEmbedded/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Public_IP_addresses_to_Log_Analytics_workspace_Deploy-Diagnostics-PublicIP/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Recovery_Services_vaults_to_Log_Analytics_workspace_Deploy-Diagnostics-RecoveryVault/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Relay_to_Log_Analytics_workspace_Deploy-Diagnostics-Relay/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Redis_Cache_to_Log_Analytics_workspace_Deploy-Diagnostics-RedisCache/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Service_Bus_namespaces_to_Log_Analytics_workspace_Deploy-Diagnostics-ServiceBus/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-SearchServices/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SignalR_to_Log_Analytics_workspace_Deploy-Diagnostics-SignalR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Databases_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLDBs/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Elastic_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLElasticPools/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Managed_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLMI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-StreamAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Time_Series_Insights_to_Log_Analytics_workspace_Deploy-Diagnostics-TimeSeriesInsights/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**'
#      - .github/workflows/manage-azure-policy-2dd4ac45.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2dd4ac45}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Diagnostic_Settings_for_Automation_to_Log_Analytics_workspace_Deploy-Diagnostics-AA/**
          policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**
          policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**
          policies/Deploy_Diagnostic_Settings_for_Activity_Log_to_Log_Analytics_workspace_Deploy-Diagnostics-ActivityLog/**
          policies/Deploy_Diagnostic_Settings_for_Kubernetes_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-AKS/**
          policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**
          policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**
          policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**
          policies/Deploy_Diagnostic_Settings_for_Batch_to_Log_Analytics_workspace_Deploy-Diagnostics-Batch/**
          policies/Deploy_Diagnostic_Settings_for_CDN_Endpoint_to_Log_Analytics_workspace_Deploy-Diagnostics-CDNEndpoints/**
          policies/Deploy_Diagnostic_Settings_for_Cognitive_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-CognitiveServices/**
          policies/Deploy_Diagnostic_Settings_for_Cosmos_DB_to_Log_Analytics_workspace_Deploy-Diagnostics-CosmosDB/**
          policies/Deploy_Diagnostic_Settings_for_Databricks_to_Log_Analytics_workspace_Deploy-Diagnostics-Databricks/**
          policies/Deploy_Diagnostic_Settings_for_Data_Factory_to_Log_Analytics_workspace_Deploy-Diagnostics-DataFactory/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Data_Lake_Store_to_Log_Analytics_workspace_Deploy-Diagnostics-DataLakeStore/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_subscriptions_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSub/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_System_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSystemTopic/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridTopic/**
          policies/Deploy_Diagnostic_Settings_for_Event_Hubs_to_Log_Analytics_workspace_Deploy-Diagnostics-EventHub/**
          policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**
          policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**
          policies/Deploy_Diagnostic_Settings_for_Front_Door_to_Log_Analytics_workspace_Deploy-Diagnostics-FrontDoor/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**
          policies/Deploy_Diagnostic_Settings_for_HDInsight_to_Log_Analytics_workspace_Deploy-Diagnostics-HDInsight/**
          policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**
          policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_Deploy-Diagnostics-KeyVault/**
          policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_integration_service_environment_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsISE/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_Workflow_runtime_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsWF/**
          policies/Deploy_Diagnostic_Settings_for_MariaDB_to_Log_Analytics_workspace_Deploy-Diagnostics-MariaDB/**
          policies/Deploy_Diagnostic_Settings_for_Machine_Learning_workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-MlWorkspace/**
          policies/Deploy_Diagnostic_Settings_for_Database_for_MySQL_to_Log_Analytics_workspace_Deploy-Diagnostics-MySQL/**
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**
          policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**
          policies/Deploy_Diagnostic_Settings_for_Database_for_PostgreSQL_to_Log_Analytics_workspace_Deploy-Diagnostics-PostgreSQL/**
          policies/Deploy_Diagnostic_Settings_for_Power_BI_Embedded_to_Log_Analytics_workspace_Deploy-Diagnostics-PowerBIEmbedded/**
          policies/Deploy_Diagnostic_Settings_for_Public_IP_addresses_to_Log_Analytics_workspace_Deploy-Diagnostics-PublicIP/**
          policies/Deploy_Diagnostic_Settings_for_Recovery_Services_vaults_to_Log_Analytics_workspace_Deploy-Diagnostics-RecoveryVault/**
          policies/Deploy_Diagnostic_Settings_for_Relay_to_Log_Analytics_workspace_Deploy-Diagnostics-Relay/**
          policies/Deploy_Diagnostic_Settings_for_Redis_Cache_to_Log_Analytics_workspace_Deploy-Diagnostics-RedisCache/**
          policies/Deploy_Diagnostic_Settings_for_Service_Bus_namespaces_to_Log_Analytics_workspace_Deploy-Diagnostics-ServiceBus/**
          policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-SearchServices/**
          policies/Deploy_Diagnostic_Settings_for_SignalR_to_Log_Analytics_workspace_Deploy-Diagnostics-SignalR/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Databases_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLDBs/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Elastic_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLElasticPools/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Managed_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLMI/**
          policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-StreamAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Time_Series_Insights_to_Log_Analytics_workspace_Deploy-Diagnostics-TimeSeriesInsights/**
          policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**
          policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**
